### ISSUE TITLE
Null exception in RoboVM plugin

### ISSUE THREAD

**Issue by ItsHarper** [robovm/robovm-idea#90] opened 2015-07-01 02:09 UTC
IDE reports the following internal error:

```
update failed for AnAction with ID=org.robovm.idea.OpenXCode: Argument for @NotNull parameter 'fileOrDir' of com/intellij/openapi/roots/impl/ModuleFileIndexImpl.isInContent must not be null
```

**Comment by ItsHarper** [comment] 2015-07-01 02:11
I am using IntelliJ 14.1.4 (EAP), and Xcode 6.4, which came out today.

**Comment by badlogic** [comment] 2015-07-01 08:05
What version is your RoboVM plugin?

**Comment by ItsHarper** [comment] 2015-07-01 12:17
1.4.0

**Comment by badlogic** [comment] 2015-07-01 12:18
Could you post the full idea logs? Couldn't reproduce it yet.

**Comment by ItsHarper** [comment] 2015-07-01 12:24
Shared with you on Google Drive.

**Comment by badlogic** [comment] 2015-07-01 13:53
Thanks!

**Comment by badlogic** [comment] 2015-07-01 13:57
Hm, the log doesn't show any suspicious errors. This happens when you double click on a storyboard file, correct?

**Comment by badlogic** [comment] 2015-07-01 14:03
I'm also running IDEA 14.1.4, but the release build, not the EAP:

![http://sht.tl/CrlqNL](http://sht.tl/CrlqNL)

Having trouble reproducing this. Two requests:
1. Could you update to the IDEA 14.1.4 release build?
2. Could you give the RoboVM IDEA plugin snapshot build a try? You can find it at http://download.robovm.org/

**Comment by ItsHarper** [comment] 2015-07-01 14:20
Honestly, I have no recollection of what I was doing when the error occurred (it happened a couple of times). Sorry :/  If I see it again, I'll make sure to let you know what I was doing. However, opening a storyboard file from IntelliJ didn't trigger it when I just tried it. Building and running the project (probably the most likely thing that I was doing the last time the error occurred) didn't trigger it either. It's either sporadic, or caused by something else.

I'm running a version with the same build number and date as you are. It was my understanding that that was an EAP build. Apparently I was wrong.

I'd be happy to try the snapshot build of the plugin, but since I don't know what's causing it, I wouldn't be able to test if it fixes the problem. And if it did fix the problem, we'd never know what the problem was. For now, I'll stay on the stable build, and watch for the error to occur again.

**Comment by badlogic** [comment] 2015-07-01 15:49
Ok, good info. I'll close this then for now. Please post here if the error
occurs again!

**Closed as completed** 2015-07-01 15:50 UTC
Labels: bug
