### ISSUE TITLE
IntelliJ plugin possible memory leak

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-idea#55] opened 2015-05-07 08:49 UTC
See robovm/robovm#971 for the original issue which was moved here. Original issue was reported by @stefanli.

**Comment by badlogic** [comment] 2015-05-15 13:28
Testing by compiling robovm-samples, various projects, release/debug mode for simulator. Process memory is growing. The JVM heap memory doesn't really grow, memory footprint returns to the same value after a forced GC via jvisualvm after 20 compilations.

Attaching Instruments to check the native side is inconclusive. The number of persisted bytes grows, but it doesn't appear that its LLVM.

**Comment by badlogic** [comment] 2015-05-15 13:32
Correction, it seems that JVM heap is indeed growing, about 10-20mb per compile...

**Comment by badlogic** [comment] 2015-08-26 16:07
Testing this via visualvm. Compiling a simple HelloWorld about 20 times, doing a manual GC after each compilation returns to the same threshold of about 503mb everytime. We are not growing in JVM heap memory.

Opening/closing new RoboVM projects also doesn't have a negative impact on JVM heap memory usage.

The process memory as reported by the activity monitor is however growing:

![http://sht.tl/g0bMGl](http://sht.tl/g0bMGl)

However, when inspecting the details of that process, OS X reports constant memory usage of about 1.3GB:

![http://sht.tl/FmRuOd](http://sht.tl/FmRuOd)

I'm inclined to think that Activity Monitor is confused in its main view. Indeed, memory usage is even decreasing over time depending on what actions are taken within IDEA in the detail view for the process.

**Comment by badlogic** [comment] 2015-08-26 16:16
20 minutes of compiling and starting an app over and over again:

![http://sht.tl/UVapAL](http://sht.tl/UVapAL)

JVM heap memory is stable. Process memory is stable. But Activity Monitor overview says process memory is growing.

![http://sht.tl/jryuUS](http://sht.tl/jryuUS)

Have not seen any detrimental effect on usability nor overall system memory. Closing this as "can't reproduce" apart from Activity Monitor reporting bogus info.

**Closed as completed by badlogic** 2015-08-26 16:16 UTC
Labels: bug
