### ISSUE TITLE
@NotNull method org/robovm/idea/running/RoboVmRunProfileState.startProcess must not return null

### ISSUE THREAD

**Issue by deadpixelsociety** [robovm/robovm-idea#97] opened 2015-07-23 14:49 UTC
We released our app and a coworker downloaded it on his iPhone 4 on which it crashes while attempting to login. It has no issues on the iPhone 4S of this kind. While attempting to debug this and find the issue I'm unable to run or debug the app from the IDE (IntelliJ w/ RoboVM 1.5 plugin). Relevant bit from idea.log:

2015-07-22 09:15:21,142 [ 204148]   INFO - lij.compiler.impl.CompilerUtil -     COMPILATION FINISHED (BUILD PROCESS); Errors: 0; warnings: 0 took 84893 ms: 1 min 24sec 
2015-07-22 09:15:38,764 [ 221770]   INFO - ellij.concurrency.JobScheduler - 50 ms execution limit failed for: com.intellij.openapi.progress.impl.CoreProgressManager$1@4629694c; elapsed time was 54ms 
2015-07-22 09:17:05,289 [ 308295]  ERROR - llij.ide.plugins.PluginManager - @NotNull method org/robovm/idea/running/RoboVmRunProfileState.startProcess must not return null 
java.lang.IllegalStateException: @NotNull method org/robovm/idea/running/RoboVmRunProfileState.startProcess must not return null
    at org.robovm.idea.running.RoboVmRunProfileState.startProcess(RoboVmRunProfileState.java:119)
    at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
    at com.intellij.debugger.DefaultDebugEnvironment.createExecutionResult(DefaultDebugEnvironment.java:46)
    at com.intellij.debugger.engine.DebugProcessImpl.attachVirtualMachine(DebugProcessImpl.java:1785)
    at com.intellij.debugger.impl.DebuggerSession.attach(DebuggerSession.java:402)
    at com.intellij.debugger.impl.DebuggerManagerImpl.attachVirtualMachine(DebuggerManagerImpl.java:243)
    at org.robovm.idea.running.RoboVmRunner.attachVirtualMachine(RoboVmRunner.java:93)
    at org.robovm.idea.running.RoboVmRunner.doExecute(RoboVmRunner.java:77)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
    at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
    at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:219)
    at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:146)
    at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:186)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:708)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
2015-07-22 09:17:05,327 [ 308333]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.4  Build #IC-141.1532.4 
2015-07-22 09:17:05,327 [ 308333]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.7.0_75 
2015-07-22 09:17:05,327 [ 308333]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-07-22 09:17:05,327 [ 308333]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2015-07-22 09:17:05,327 [ 308333]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2015-07-22 09:17:05,327 [ 308333]  ERROR - llij.ide.plugins.PluginManager - Last Action: Debug

**Comment by badlogic** [comment] 2015-07-29 09:07
Could you post the log from the RoboVM console view from Eclipse? The method in question throws an exception that is caught and logged to that view, but doesn't turn up in the IDEA logs.

**Comment by badlogic** [comment] 2015-08-04 10:50
Can't reproduce, closing this out for now. @deadpixelsociety please update with the requested information and we can open it up again.

**Closed as completed by badlogic** 2015-08-04 10:50 UTC
Labels: bug, waiting for information

**Comment by oliver124810** [comment] 2015-10-13 16:41
For anyone having the same issue, check if you don't have the following error message above (easily overseen due to the scrolling):

```
[ERROR] Couldn't start application
org.robovm.libimobiledevice.LibIMobileDeviceException: DeviceOSVersionTooLow
    at org.robovm.libimobiledevice.util.AppLauncher$1.error(AppLauncher.java:1001)
    at org.robovm.libimobiledevice.Callbacks.callInstproxyCallback(Callbacks.java:64)
```

In this case, you just have to reduce the MinimumOSVersion in info.plist.xml according to the iOS version of your target device.
