### ISSUE TITLE
Error when adding a RoboVM module to a project

### ISSUE THREAD

**Issue by ajhager** [robovm/robovm-idea#66] opened 2015-05-27 19:15 UTC
## New Module

_Error adding module to project: Parameter 'directory' is not a directory._

It doesn't seem to affect anything, but is bad for user experience.

**Comment by badlogic** [comment] 2015-05-28 12:04
If possible, please always post the full stack trace.

Overlooked this, i should have fixed it for 1.3 :/

**Comment by badlogic** [comment] 2015-05-28 12:10
Couldn't reproduce this one.

**Comment by ajhager** [comment] 2015-05-28 12:19
Sorry, It wasn't a stack trace. It is a small IntelliJ popup. I just started seeing in a snapshot build of the idea plugin (I think.) I will debug this on my machine.

**Comment by badlogic** [comment] 2015-08-06 12:40
This should be fixed.

**Closed as completed by badlogic** 2015-08-06 12:40 UTC
Labels: bug
